version: '3'

services:
  kolibri:
    image: learningequality/kolibri:latest
    container_name: kolibri
    ports:
      - "8080:8080"
    environment:
      - KOLIBRI_HOME=/kolibri_data
      - KOLIBRI_HTTP_PORT=8080
      - KOLIBRI_LANG=${KOLIBRI_LANG:-en}
      - KOLIBRI_PROVISIONDEVICE_FACILITY=${KOLIBRI_FACILITY:-Community Learning Center}
      - KOLIBRI_PROVISIONDEVICE_PRESET=${KOLIBRI_PRESET:-formal}
      - KOLIBRI_PROVISIONDEVICE_SUPERUSERNAME=${KOLIBRI_ADMIN_USER:-admin}
      - KOLIBRI_PROVISIONDEVICE_SUPERUSERPASSWORD=${KOLIBRI_ADMIN_PASSWORD:-password}
    volumes:
      - kolibri_data:/kolibri_data
      - ./content:/content # Optional: mount a directory with pre-downloaded content
    restart: unless-stopped
    networks:
      - education_network

volumes:
  kolibri_data:

networks:
  education_network:
    driver: bridge
