version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      TZ: ${TZ:-UTC}
      WEBPASSWORD: ${PIHOLE_PASSWORD:-password}
      ServerIP: ${SERVER_IP:-192.168.1.10} # Replace with your server's IP
      DNS1: 1.1.1.1 # Cloudflare
      DNS2: 8.8.8.8 # Google
      # WEBTHEME: default-dark # Optional: dark theme
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - filtering_network

volumes:
  pihole_etc:
  pihole_dnsmasq:

networks:
  filtering_network:
    driver: bridge
