version: '3'

services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
      - "8765:80"
    environment:
      - TZ=${TZ:-UTC}
      - PUID=1000
      - PGID=1000
      - OOKLA_EULA_ACCEPTED=true # Accept Ookla EULA
    volumes:
      - speedtest_config:/config
    restart: unless-stopped
    networks:
      - monitoring_network

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - monitoring_network

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring_network

volumes:
  speedtest_config:
  prometheus_data:
  grafana_data:

networks:
  monitoring_network:
    driver: bridge
